spring.application.name=SpringEcommerce

spring.datasource.url=jdbc:postgresql://localhost:5432/springDatabase
spring.datasource.username=postgres
spring.datasource.password=ManthanP@0110
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update